spring.application.name=SpringJPA

springdoc.swagger-ui.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=bao041012

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
